source "http://rubygems.org"
gem 'nokogiri', '1.6.1'
gem 'cucumber'
gem 'bddfire'
gem 'selenium-webdriver'
gem 'rake'
gem 'yard-cucumber'
gem 'cuke_sniffer'
gem 'json'
gem 'rspec'
gem 'relish'
gem 'rubocop-checkstyle_formatter'
gem 'selenium_fury'
gem 'simplecov'
gem 'faker'
gem 'parallel_tests'
gem 'selendroid'
gem 'headless'
